---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/prof2543/public_html/gestaotrafego/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R cron $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/rm -f $DEPLOYPATH/diagnostico.php
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp README_PRO.md $DEPLOYPATH
