/* Execute este arquivo dentro do banco prof2543_meta_ads_manager */

CREATE TABLE IF NOT EXISTS meta_integrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    app_id VARCHAR(100) DEFAULT NULL,
    app_secret VARCHAR(255) DEFAULT NULL,
    access_token TEXT DEFAULT NULL,
    ad_account_id VARCHAR(50) NOT NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    sync_interval_minutes INT UNSIGNED NOT NULL DEFAULT 30,
    timezone VARCHAR(100) DEFAULT 'America/Sao_Paulo',
    currency_code VARCHAR(3) NOT NULL DEFAULT 'BRL',
    currency_spread_percent DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
    manual_exchange_rate DECIMAL(12,6) DEFAULT NULL,
    last_sync_at DATETIME NULL,
    last_success_sync_at DATETIME NULL,
    last_error_at DATETIME NULL,
    last_error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_status (status),
    KEY idx_ad_account_id (ad_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_sync_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    integration_id BIGINT UNSIGNED NOT NULL,
    scope ENUM('account','campaign','adset','ad') NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    status ENUM('running','success','error') NOT NULL DEFAULT 'running',
    rows_upserted INT UNSIGNED NOT NULL DEFAULT 0,
    message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_integration_id (integration_id),
    KEY idx_scope (scope),
    KEY idx_status (status),
    KEY idx_date_range (date_from, date_to),
    CONSTRAINT fk_meta_sync_runs_integration FOREIGN KEY (integration_id) REFERENCES meta_integrations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_account_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    integration_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    account_id VARCHAR(50) NOT NULL,
    account_name VARCHAR(255) DEFAULT NULL,
    spend DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reach BIGINT UNSIGNED NOT NULL DEFAULT 0,
    frequency DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unique_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    inline_link_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    outbound_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    landing_page_views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ctr DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    cpc DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    cpm DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchases BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchase_value DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    purchase_roas DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    raw_actions_json LONGTEXT NULL,
    raw_cost_per_action_json LONGTEXT NULL,
    raw_purchase_roas_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_account_daily (integration_id, report_date, account_id),
    KEY idx_report_date (report_date),
    KEY idx_account_id (account_id),
    CONSTRAINT fk_meta_account_daily_integration FOREIGN KEY (integration_id) REFERENCES meta_integrations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_campaign_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    integration_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    account_id VARCHAR(50) NOT NULL,
    campaign_id VARCHAR(50) NOT NULL,
    campaign_name VARCHAR(255) DEFAULT NULL,
    objective VARCHAR(100) DEFAULT NULL,
    buying_type VARCHAR(100) DEFAULT NULL,
    status VARCHAR(50) DEFAULT NULL,
    effective_status VARCHAR(50) DEFAULT NULL,
    spend DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reach BIGINT UNSIGNED NOT NULL DEFAULT 0,
    frequency DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unique_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    inline_link_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    outbound_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    landing_page_views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ctr DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    cpc DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    cpm DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchases BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchase_value DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    purchase_roas DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    raw_actions_json LONGTEXT NULL,
    raw_cost_per_action_json LONGTEXT NULL,
    raw_purchase_roas_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_campaign_daily (integration_id, report_date, campaign_id),
    KEY idx_report_date (report_date),
    KEY idx_campaign_id (campaign_id),
    KEY idx_account_id (account_id),
    KEY idx_campaign_name (campaign_name),
    CONSTRAINT fk_meta_campaign_daily_integration FOREIGN KEY (integration_id) REFERENCES meta_integrations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_adset_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    integration_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    account_id VARCHAR(50) NOT NULL,
    campaign_id VARCHAR(50) NOT NULL,
    campaign_name VARCHAR(255) DEFAULT NULL,
    adset_id VARCHAR(50) NOT NULL,
    adset_name VARCHAR(255) DEFAULT NULL,
    status VARCHAR(50) DEFAULT NULL,
    effective_status VARCHAR(50) DEFAULT NULL,
    spend DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reach BIGINT UNSIGNED NOT NULL DEFAULT 0,
    frequency DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unique_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    inline_link_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    outbound_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    landing_page_views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ctr DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    cpc DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    cpm DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchases BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchase_value DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    purchase_roas DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    raw_actions_json LONGTEXT NULL,
    raw_cost_per_action_json LONGTEXT NULL,
    raw_purchase_roas_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_adset_daily (integration_id, report_date, adset_id),
    KEY idx_report_date (report_date),
    KEY idx_campaign_id (campaign_id),
    KEY idx_adset_id (adset_id),
    KEY idx_account_id (account_id),
    KEY idx_adset_name (adset_name),
    CONSTRAINT fk_meta_adset_daily_integration FOREIGN KEY (integration_id) REFERENCES meta_integrations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_ad_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    integration_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    account_id VARCHAR(50) NOT NULL,
    campaign_id VARCHAR(50) NOT NULL,
    campaign_name VARCHAR(255) DEFAULT NULL,
    adset_id VARCHAR(50) NOT NULL,
    adset_name VARCHAR(255) DEFAULT NULL,
    ad_id VARCHAR(50) NOT NULL,
    ad_name VARCHAR(255) DEFAULT NULL,
    status VARCHAR(50) DEFAULT NULL,
    effective_status VARCHAR(50) DEFAULT NULL,
    spend DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reach BIGINT UNSIGNED NOT NULL DEFAULT 0,
    frequency DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unique_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    inline_link_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    outbound_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    landing_page_views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ctr DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    cpc DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    cpm DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchases BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchase_value DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    purchase_roas DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    raw_actions_json LONGTEXT NULL,
    raw_cost_per_action_json LONGTEXT NULL,
    raw_purchase_roas_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ad_daily (integration_id, report_date, ad_id),
    KEY idx_report_date (report_date),
    KEY idx_campaign_id (campaign_id),
    KEY idx_adset_id (adset_id),
    KEY idx_ad_id (ad_id),
    KEY idx_account_id (account_id),
    KEY idx_ad_name (ad_name),
    CONSTRAINT fk_meta_ad_daily_integration FOREIGN KEY (integration_id) REFERENCES meta_integrations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attribution_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_type ENUM('import','match','daily') NOT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    status ENUM('running','success','error') NOT NULL DEFAULT 'running',
    stats_json LONGTEXT NULL,
    message TEXT NULL,
    PRIMARY KEY (id),
    KEY idx_run_type (run_type),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attribution_leads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_user_id BIGINT UNSIGNED NOT NULL,
    lead_name VARCHAR(255) DEFAULT NULL,
    lead_name_norm VARCHAR(255) DEFAULT NULL,
    lead_email VARCHAR(255) DEFAULT NULL,
    lead_email_norm VARCHAR(255) DEFAULT NULL,
    lead_phone_raw VARCHAR(50) DEFAULT NULL,
    lead_phone_norm VARCHAR(20) DEFAULT NULL,
    turma_codigo VARCHAR(50) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    utm_source VARCHAR(255) DEFAULT NULL,
    utm_source_norm VARCHAR(255) DEFAULT NULL,
    utm_campaign_group VARCHAR(255) DEFAULT NULL,
    utm_campaign_group_norm VARCHAR(255) DEFAULT NULL,
    utm_campaign_name VARCHAR(255) DEFAULT NULL,
    utm_campaign_name_norm VARCHAR(255) DEFAULT NULL,
    utm_ad_name VARCHAR(255) DEFAULT NULL,
    utm_ad_name_norm VARCHAR(255) DEFAULT NULL,
    utm_term VARCHAR(255) DEFAULT NULL,
    utm_term_norm VARCHAR(255) DEFAULT NULL,
    imported_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_user_id (source_user_id),
    KEY idx_created_at (created_at),
    KEY idx_lead_phone_norm (lead_phone_norm),
    KEY idx_lead_email_norm (lead_email_norm),
    KEY idx_campaign_group_norm (utm_campaign_group_norm),
    KEY idx_campaign_name_norm (utm_campaign_name_norm),
    KEY idx_ad_name_norm (utm_ad_name_norm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attribution_sales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_sale_id BIGINT UNSIGNED NOT NULL,
    transaction_code VARCHAR(80) DEFAULT NULL,
    sale_status VARCHAR(50) DEFAULT NULL,
    sale_date DATETIME NOT NULL,
    payment_confirmed_at DATETIME NULL,
    product_code VARCHAR(80) DEFAULT NULL,
    product_name VARCHAR(255) DEFAULT NULL,
    price_name VARCHAR(255) DEFAULT NULL,
    currency VARCHAR(10) DEFAULT NULL,
    gross_revenue DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    net_revenue DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    producer_net DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    buyer_name VARCHAR(255) DEFAULT NULL,
    buyer_name_norm VARCHAR(255) DEFAULT NULL,
    buyer_email VARCHAR(255) DEFAULT NULL,
    buyer_email_norm VARCHAR(255) DEFAULT NULL,
    buyer_phone_raw VARCHAR(50) DEFAULT NULL,
    buyer_phone_norm VARCHAR(20) DEFAULT NULL,
    matched_user_id BIGINT UNSIGNED DEFAULT NULL,
    match_method VARCHAR(30) DEFAULT NULL,
    utm_source VARCHAR(255) DEFAULT NULL,
    utm_source_norm VARCHAR(255) DEFAULT NULL,
    utm_campaign_group VARCHAR(255) DEFAULT NULL,
    utm_campaign_group_norm VARCHAR(255) DEFAULT NULL,
    utm_campaign_name VARCHAR(255) DEFAULT NULL,
    utm_campaign_name_norm VARCHAR(255) DEFAULT NULL,
    utm_ad_name VARCHAR(255) DEFAULT NULL,
    utm_ad_name_norm VARCHAR(255) DEFAULT NULL,
    utm_term VARCHAR(255) DEFAULT NULL,
    utm_term_norm VARCHAR(255) DEFAULT NULL,
    imported_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_sale_id (source_sale_id),
    KEY idx_sale_date (sale_date),
    KEY idx_buyer_phone_norm (buyer_phone_norm),
    KEY idx_buyer_email_norm (buyer_email_norm),
    KEY idx_matched_user_id (matched_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attribution_matches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sale_id BIGINT UNSIGNED NOT NULL,
    lead_id BIGINT UNSIGNED NOT NULL,
    attribution_model ENUM('first_touch','last_touch') NOT NULL,
    match_type VARCHAR(30) NOT NULL,
    attribution_seconds_diff BIGINT UNSIGNED NOT NULL DEFAULT 0,
    lead_created_at DATETIME NOT NULL,
    sale_date DATETIME NOT NULL,
    campaign_group VARCHAR(255) DEFAULT NULL,
    campaign_group_norm VARCHAR(255) DEFAULT NULL,
    campaign_name VARCHAR(255) DEFAULT NULL,
    campaign_name_norm VARCHAR(255) DEFAULT NULL,
    ad_name VARCHAR(255) DEFAULT NULL,
    ad_name_norm VARCHAR(255) DEFAULT NULL,
    revenue_value DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    product_name VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sale_model (sale_id, attribution_model),
    KEY idx_lead_id (lead_id),
    KEY idx_sale_date (sale_date),
    KEY idx_campaign_group_norm (campaign_group_norm),
    KEY idx_campaign_name_norm (campaign_name_norm),
    KEY idx_ad_name_norm (ad_name_norm),
    CONSTRAINT fk_attribution_matches_sale FOREIGN KEY (sale_id) REFERENCES attribution_sales(id) ON DELETE CASCADE,
    CONSTRAINT fk_attribution_matches_lead FOREIGN KEY (lead_id) REFERENCES attribution_leads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attribution_campaign_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_date DATE NOT NULL,
    attribution_model ENUM('first_touch','last_touch') NOT NULL,
    campaign_group VARCHAR(255) DEFAULT NULL,
    campaign_group_norm VARCHAR(255) DEFAULT NULL,
    campaign_name VARCHAR(255) DEFAULT NULL,
    campaign_name_norm VARCHAR(255) DEFAULT NULL,
    ad_name VARCHAR(255) DEFAULT NULL,
    ad_name_norm VARCHAR(255) DEFAULT NULL,
    meta_spend DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reach BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    frequency DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    cpm DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    cpc DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    ctr DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attributed_sales BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attributed_revenue DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    cpl DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    cac DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    roas DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_attr_daily (report_date, attribution_model, campaign_group_norm, campaign_name_norm, ad_name_norm),
    KEY idx_report_model (report_date, attribution_model),
    KEY idx_campaign_group_norm (campaign_group_norm),
    KEY idx_campaign_name_norm (campaign_name_norm),
    KEY idx_ad_name_norm (ad_name_norm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
