CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    telefone VARCHAR(80) DEFAULT NULL,
    codigo_turma VARCHAR(80) DEFAULT NULL,
    utm_source VARCHAR(255) DEFAULT NULL,
    utm_medium VARCHAR(255) DEFAULT NULL,
    utm_campaign VARCHAR(255) DEFAULT NULL,
    utm_term VARCHAR(255) DEFAULT NULL,
    utm_content VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_users_email (email),
    KEY idx_users_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hotmart_sales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transaction_code VARCHAR(80) NOT NULL,
    status VARCHAR(60) DEFAULT NULL,
    transaction_date DATETIME NOT NULL,
    payment_confirmed_at DATETIME NULL,
    product_code VARCHAR(80) DEFAULT NULL,
    product_name VARCHAR(255) DEFAULT NULL,
    price_code VARCHAR(80) DEFAULT NULL,
    price_name VARCHAR(255) DEFAULT NULL,
    currency VARCHAR(10) DEFAULT 'BRL',
    gross_revenue DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    net_revenue DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    producer_net DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    buyer_name VARCHAR(255) DEFAULT NULL,
    buyer_email VARCHAR(255) DEFAULT NULL,
    buyer_phone_raw VARCHAR(80) DEFAULT NULL,
    buyer_phone_norm VARCHAR(20) DEFAULT NULL,
    matched_user_id BIGINT UNSIGNED DEFAULT NULL,
    match_method VARCHAR(30) DEFAULT NULL,
    utm_source VARCHAR(255) DEFAULT NULL,
    utm_medium VARCHAR(255) DEFAULT NULL,
    utm_campaign VARCHAR(255) DEFAULT NULL,
    utm_term VARCHAR(255) DEFAULT NULL,
    utm_content VARCHAR(255) DEFAULT NULL,
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hotmart_sales_transaction (transaction_code),
    KEY idx_transaction_date (transaction_date),
    KEY idx_payment_confirmed_at (payment_confirmed_at),
    KEY idx_status (status),
    KEY idx_buyer_email (buyer_email),
    KEY idx_buyer_phone_norm (buyer_phone_norm),
    KEY idx_matched_user_id (matched_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

